title: Manish S. Devana
url: "https://msdevana.github.io/"
baseurl: "/digital-CV"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
  style: compressed
  sass_dir: _sass
